#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-test-interface
Version  : 1.0
Release  : 1
URL      : https://repo1.maven.org/maven2/org/scala-sbt/test-interface/1.0/test-interface-1.0.jar
Source0  : https://repo1.maven.org/maven2/org/scala-sbt/test-interface/1.0/test-interface-1.0.jar
Source1  : https://repo1.maven.org/maven2/org/scala-sbt/test-interface/1.0/test-interface-1.0.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-3-Clause
Requires: mvn-test-interface-data = %{version}-%{release}

%description
No detailed description available

%package data
Summary: data components for the mvn-test-interface package.
Group: Data

%description data
data components for the mvn-test-interface package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/scala-sbt/test-interface/1.0
cp %{SOURCE0} %{buildroot}/usr/share/java/.m2/repository/org/scala-sbt/test-interface/1.0/test-interface-1.0.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/scala-sbt/test-interface/1.0
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/scala-sbt/test-interface/1.0/test-interface-1.0.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/scala-sbt/test-interface/1.0/test-interface-1.0.jar
/usr/share/java/.m2/repository/org/scala-sbt/test-interface/1.0/test-interface-1.0.pom
